export const Movies=[
      {
        duration: 120,
        id: 2,
        countryoforigin: "France",
        description: "Portrait of a Lady on Fire is a French historical drama film directed by Céline Sciamma. Set in France in the late 18th century, the story revolves around Marianne, a young painter, who is commissioned to create a portrait of Héloïse, a woman soon to be married. Héloïse, however, refuses to sit for the portrait, leading Marianne to observe her subject in secret during their daily walks. As they spend more time together, a forbidden romance blossoms between the two women, challenging societal norms and expectations.",
        director: "Céline Sciamma",
        genre: "Drama",
        language: "French",
        title: "Portrait of a Lady on Fire",
        trailer: "https://www.youtube.com/watch?v=R-fQPTwma9o",
        poster: "https://i.pinimg.com/564x/37/e3/b3/37e3b3b0a295ac155f876511d42eef64.jpg",
        yearofrelease: 2019,
        nowPlaying:true
      },
      {
        duration: 158,
        id: 3,
        countryoforigin: "USA",
        description: "Tar starring Cate Blanchett is a biographical drama film depicting the life of American artist Georgia O'Keeffe. It delves into her influential career in modern art and explores her intricate relationship with her husband, photographer Alfred Stieglitz. Through Cate Blanchett's compelling performance, Tar offers a captivating portrayal of O'Keeffe's artistic journey and personal struggles.",
        director: "Todd Field",
        genre: "Drama",
        language: "English",
        title: "Tár",
        trailer: "https://www.youtube.com/watch?v=0ueOnKPiqGY",
        poster: "https://i.pinimg.com/564x/ef/2b/f5/ef2bf56fdc2d401c901746c58d0db030.jpg",
        yearofrelease: 2022,
        nowPlaying:true
      },
      {
        duration: 86,
        id: 4,
        countryoforigin: "USA",
        description: "Frances Ha is a black-and-white comedy-drama film directed by Noah Baumbach. It follows the story of Frances, a 27-year-old dancer living in New York City, as she navigates through her friendships, career aspirations, and personal growth. The film offers a candid and humorous exploration of adulthood, independence, and the pursuit of one's dreams, portrayed through Frances's quirky and endearing character.",
        director: " Noah Baumbach",
        genre: "Drama",
        language: "English",
        title: "Frances Ha",
        trailer: "https://www.youtube.com/watch?v=YdxCnCvCngk",
        poster: "https://i.pinimg.com/564x/07/8f/39/078f39230d6c557521e5ff97433673cd.jpg",
        yearofrelease: 2012,
        nowPlaying:true
      },
      {
        duration: 99,
        id: 5,
        countryoforigin: "USA",
        description: "Reservoir Dogs is a gripping crime thriller directed by Quentin Tarantino. The film follows a group of criminals, each identified by a color-coded pseudonym, as they navigate the aftermath of a botched jewelry heist. Tensions rise as suspicion mounts, leading to a series of intense confrontations and betrayals. With its nonlinear narrative and raw dialogue, Reservoir Dogs is a visceral exploration of loyalty, deception, and the gritty underworld of organized crime.",
        director: "Quentin Tarantino",
        genre: "Crime",
        language: "English",
        title: "Reservoir Dogs",
        trailer: "https://www.youtube.com/watch?v=vayksn4Y93A",
        poster: "https://i.pinimg.com/564x/51/20/eb/5120eb35e36f5b1f6a91291538318c05.jpg",
        yearofrelease: 1992,
        nowPlaying:true
      },
      {
        duration: 161,
        id: 6,
        countryoforigin: "USA",
        description: "Amadeus is a historical drama film that delves into the life of Wolfgang Amadeus Mozart, the prolific and genius composer of the classical era. Set in Vienna, the story is narrated by Antonio Salieri, a contemporary composer who becomes consumed by jealousy and resentment towards Mozart's unmatched talent. The film explores themes of genius, rivalry, and the pursuit of artistic excellence amidst the backdrop of 18th-century Europe.",
        director: "Miloš Forman",
        genre: "Drama",
        language: "English",
        title: "Amadeus",
        trailer: "https://www.youtube.com/watch?v=r7kWQj9FCGY",
        poster: "https://i.pinimg.com/564x/6f/3a/2d/6f3a2d5f53335539acfb1eb3ce20c42a.jpg",
        yearofrelease: 1984,
        nowPlaying:true
      },
      {
        duration: 94,
        id: 7,
        countryoforigin: "UK",
        description: "Clue is a comedic mystery film based on the popular board game of the same name. Set in a mansion during a stormy night, the movie follows a group of guests who become embroiled in a series of murders. Filled with witty humor and eccentric characters, Clue keeps viewers guessing until the very end as they try to uncover the identity of the killer.",
        director: "Jonathan Lynn",
        genre: "Mystery",
        language: "English",
        title: "Clue",
        trailer: "https://www.youtube.com/watch?v=KEXdWfsKZ1k",
        poster: "https://i.pinimg.com/564x/4c/55/dc/4c55dcc0abe11cf7972a0ef728440252.jpg",
        yearofrelease: 1985,
        nowPlaying:true
  },
  {
    duration: 159,
    id: 8,
    countryoforigin: "UK",
    description: "Dr. Bill Harford's world is shaken when his wife, Alice, confesses her hidden desires for another man, sparking a journey into the depths of desire and obsession. In pursuit of his own erotic odyssey, Bill stumbles upon an underground society shrouded in mystery and secrecy. As he delves deeper into this clandestine world of forbidden pleasures, he finds himself drawn into a labyrinth of temptation and danger, where the boundaries between reality and fantasy blur, and the consequences of his actions become increasingly uncertain.",
    director: "Stanley Kubrick",
    genre: "Thriller",
    language: "English",
    title: "Eyes Wide Shut",
    trailer: "https://www.youtube.com/watch?v=xgVo96JaqeM",
    poster: "https://i.pinimg.com/564x/fe/96/38/fe96381e8a6d523a2409509578a42113.jpg",
    yearofrelease: 1999,
    nowPlaying:true
  },
  {
    duration: 142,
    id: 9,
    countryoforigin: "Japan",
    description: "In High and Low, an executive of a shoe company becomes entangled in a gripping tale of extortion when his chauffeur’s son is kidnapped and held for ransom. As the tension rises, the film delves into the depths of moral ambiguity and the human psyche, exploring the complexities of guilt, responsibility, and the lengths one would go to protect their own. With masterful direction by Akira Kurosawa, this crime thriller unfolds with suspense and intrigue, keeping audiences on the edge of their seats until the very end.",
    director: "Akira Kurosawa",
    genre: "Crime",
    language: "Japanese",
    title: "High and Low",
    trailer: "https://www.youtube.com/watch?v=LV3z2Ytxu90",
    poster: "https://i.pinimg.com/736x/c6/2d/a4/c62da472e58da0b2904f69d2be97b96b.jpg",
    yearofrelease: 1963,
    nowPlaying:true
  },
  {
    duration: 111,
    id: 10,
    countryoforigin: "USA",
    description: "In Rebel Without a Cause, Jim Stark, a rebellious teenager, relocates to a new town with the hope of starting afresh. However, his journey takes an unexpected turn as he grapples with the complexities of fitting in and navigating the turbulent dynamics of adolescence. Amidst the pressures of societal expectations and the allure of youthful rebellion, Jim embarks on a quest for identity and belonging, confronting inner turmoil and external conflicts along the way. As he forms unlikely alliances and confronts his inner demons, Jim's journey serves as a poignant exploration of teenage angst, the search for authenticity, and the quest for self-discovery in a world defined by conformity and rebellion.",
    director: "Nicholas Ray",
    genre: "Drama",
    language: "English",
    title: "Rebel Without a Cause",
    trailer: "https://youtube.com/watch?v=HWHH5TwEwtI",
    poster: "https://i.pinimg.com/564x/7e/f6/d0/7ef6d081db2ac0c3df29f27a293bc786.jpg",
    yearofrelease: 1955,
    nowPlaying:false
  },
  {
    duration: 147,
    id: 11,
    countryoforigin: "USA",
    description: "In Midsommar, several friends embark on a journey to Sweden to study an intriguing summer festival. However, what initially seems like an idyllic vacation soon takes a dark turn as they become involved in the disturbing and enigmatic rituals of the festival's mysterious inhabitants. As the sun never sets in this remote village, the boundaries between reality and nightmare blur, leading to a surreal and unsettling experience for the unsuspecting visitors..",
    director: "Ari Aster",
    genre: "Horror",
    language: "English",
    title: "Midsommar",
    trailer: "https://www.youtube.com/watch?v=1Vnghdsjmd0",
    poster: "https://i.pinimg.com/564x/a8/8d/43/a88d431574154f9c246a1daa8eae5b88.jpg",
    yearofrelease: 2019,
    nowPlaying:false
  },
  {
    duration: 228,
    id: 12,
    countryoforigin: "UK",
    description: "In Lawrence of Arabia, embark on an epic journey alongside British officer T.E. Lawrence as he navigates the deserts of the Middle East during World War I. Witness his transformation from a mere soldier to a larger-than-life figure leading Arab tribes against the Ottoman Empire. Experience the turmoil of war, the complexities of alliances, and the personal struggles of a man torn between duty and his own psyche. Directed by David Lean, this timeless masterpiece immerses you in a world of adventure, betrayal, and the quest for freedom.",
    director: "David Lean",
    genre: "Adventure",
    language: "English",
    title: "Lawrence of Arabia",
    trailer: "https://www.youtube.com/watch?v=vOlRhGEhG7k",
    poster: "https://i.pinimg.com/564x/c3/da/c1/c3dac153eb138411fcf45eeca11feea1.jpg",
    yearofrelease: 1962,
    nowPlaying:false
  },
  {
    duration: 147,
    id: 13,
    countryoforigin: "USA",
    description: "In Mulholland Drive, a captivating mystery unfolds as Betty Elms, a hopeful Hollywood newcomer, encounters a mysterious amnesiac brunette. Their intertwined journey leads them through the labyrinthine streets of Los Angeles, where hidden desires and dark secrets lurk beneath the glamorous surface. Meanwhile, filmmaker Adam Kesher grapples with the sinister forces threatening his latest project, as the boundaries between reality and illusion blur in this surreal tale of identity, ambition, and obsession.",
    director: "David Lynch",
    genre: "Mystery",
    language: "English",
    title: "Mulholland Drive",
    trailer: "https://www.youtube.com/watch?v=jbZJ487oJlY",
    poster: "https://i.pinimg.com/564x/40/26/b3/4026b34a69364053bd86297d9ffc4963.jpg",
    yearofrelease: 2001,
    nowPlaying:false
  },
  {
    duration: 125,
    id: 14,
    countryoforigin: "Japan",
    description: "In Spirited Away, a young girl named Chihiro finds herself trapped in a mysterious world filled with spirits. When her parents undergo a puzzling transformation, Chihiro must summon her inner courage to navigate this strange realm and free her family. Along the way, she encounters various fantastical creatures and faces daunting challenges that test her resilience and determination. Directed by Hayao Miyazaki, this enchanting tale explores themes of courage, resilience, and the power of the human spirit to overcome adversity.",
    director: "Hayao Miyazaki",
    genre: "Fantasy",
    language: "Japanese",
    title: "Spirited Away",
    trailer: "https://www.youtube.com/watch?v=ByXuk9QqQkk&t=33s",
    poster: "https://i.pinimg.com/564x/7b/20/60/7b2060adf9cb7dd2613aefced8528e77.jpg",
    yearofrelease: 2001,
    nowPlaying:false
  },
  {
    duration: 97,
    id: 15,
    countryoforigin: "USA",
    description: "In 12 Angry Men, a gripping courtroom drama unfolds as twelve jurors deliberate the fate of a young Spanish-American boy accused of murdering his father. As tensions rise and tempers flare within the jury room, the seemingly straightforward case becomes a compelling exploration of justice, prejudice, and the human condition. Each juror's unique perspective and personal biases come to light, revealing the complexities of the legal system and the weighty responsibility of determining a man's innocence or guilt. Through intense deliberation and impassioned debate, the jurors must confront their own prejudices and confront the truth amidst overwhelming pressure to reach a unanimous verdict. With its riveting storyline and powerful performances, 12 Angry Men is a timeless tale of morality, integrity, and the pursuit of justice.",
    director: "Sidney Lumet",
    genre: "Drama",
    language: "English",
    title: "12 Angry Men",
    trailer: "https://www.youtube.com/watch?v=TEN-2uTi2c0",
    poster: "https://i.pinimg.com/564x/ca/38/da/ca38dacb6584c1eb204b052b6ee796cf.jpg",
    yearofrelease: 1957,
    nowPlaying:false
  },
  {
    duration: 142,
    id: 16,
    countryoforigin: "USSR",
    description: "In Come and See, we are thrust into the harrowing reality of war as we follow the journey of young Florya amidst the devastation of his village by German forces in Byelorussia. Against the backdrop of chaos and despair, Florya embarks on a perilous odyssey, joining the ranks of weary Resistance fighters despite the vehement objections of his family. As the horrors of war unfold before him, Florya is forced to confront the brutal truths of conflict, survival, and the indomitable human spirit amidst the darkest of circumstances.",
    director: "Elem Klimov",
    genre: "War",
    language: "Russian",
    title: "Come and See",
    trailer: "https://www.youtube.com/watch?v=UHaSQU-4wss",
    poster: "https://i.pinimg.com/564x/39/aa/df/39aadf148fa4ff28791dbd13a8ead8ac.jpg",
    yearofrelease: 1985,
    nowPlaying:false
  },
  {
    duration: 124,
    id: 17,
    countryoforigin: "USA",
    description: "In Cabaret, immerse yourself in the vibrant atmosphere of 1931 Berlin's Kit Kat Club, where starry-eyed singer Sally Bowles and an impish emcee beckon audiences into a world of decadent fun. Outside, the looming presence of a rising political force casts a shadow over the revelry, creating a captivating backdrop for this musical exploration of love, desire, and the pursuit of pleasure in a time of upheaval.",
    director: "Bob Fosse",
    genre: "Musical",
    language: "English",
    title: "Cabaret",
    trailer: "https://www.youtube.com/watch?v=EfL1J4QVhSM",
    poster: "https://i.pinimg.com/564x/81/0c/51/810c5161c8dc2e77214e96762b207a07.jpg",
    yearofrelease: 1972,
    nowPlaying:false
  }
]
